"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class DirectChatMessageRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SENDER_EMAIL_FIELD_NUMBER: builtins.int
    RECEIVER_EMAIL_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    sender_email: builtins.str
    receiver_email: builtins.str
    message: builtins.str
    def __init__(
        self,
        *,
        sender_email: builtins.str = ...,
        receiver_email: builtins.str = ...,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["message", b"message", "receiver_email", b"receiver_email", "sender_email", b"sender_email"]) -> None: ...

Global___DirectChatMessageRequest: typing_extensions.TypeAlias = DirectChatMessageRequest

@typing.final
class Response(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGE_FIELD_NUMBER: builtins.int
    message: builtins.str
    def __init__(
        self,
        *,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["message", b"message"]) -> None: ...

Global___Response: typing_extensions.TypeAlias = Response
