# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: authentication.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'authentication.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x61uthentication.proto\x12\x19UserAuthenticationService\"3\n\tUserCheck\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x17\n\x0fhashed_password\x18\x03 \x01(\t\"B\n\nUserCreate\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x17\n\x0fhashed_password\x18\x03 \x01(\t\"\x1b\n\x08Response\x12\x0f\n\x07message\x18\x01 \x01(\t2\xc3\x01\n\x12UserAuthentication\x12V\n\x06signup\x12%.UserAuthenticationService.UserCreate\x1a#.UserAuthenticationService.Response\"\x00\x12U\n\x06signin\x12$.UserAuthenticationService.UserCheck\x1a#.UserAuthenticationService.Response\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'authentication_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERCHECK']._serialized_start=51
  _globals['_USERCHECK']._serialized_end=102
  _globals['_USERCREATE']._serialized_start=104
  _globals['_USERCREATE']._serialized_end=170
  _globals['_RESPONSE']._serialized_start=172
  _globals['_RESPONSE']._serialized_end=199
  _globals['_USERAUTHENTICATION']._serialized_start=202
  _globals['_USERAUTHENTICATION']._serialized_end=397
# @@protoc_insertion_point(module_scope)
