# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chat_deliver.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'chat_deliver.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63hat_deliver.proto\x12\x11\x44irectChatService\"Y\n\x18\x44irectChatMessageRequest\x12\x14\n\x0csender_email\x18\x01 \x01(\t\x12\x16\n\x0ereceiver_email\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"\x1b\n\x08Response\x12\x0f\n\x07message\x18\x02 \x01(\t2g\n\nDirectChat\x12Y\n\x0bSendMessage\x12+.DirectChatService.DirectChatMessageRequest\x1a\x1b.DirectChatService.Response\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_deliver_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DIRECTCHATMESSAGEREQUEST']._serialized_start=41
  _globals['_DIRECTCHATMESSAGEREQUEST']._serialized_end=130
  _globals['_RESPONSE']._serialized_start=132
  _globals['_RESPONSE']._serialized_end=159
  _globals['_DIRECTCHAT']._serialized_start=161
  _globals['_DIRECTCHAT']._serialized_end=264
# @@protoc_insertion_point(module_scope)
