# ----------- UPSTREAMS -----------
upstream auth_service {
    least_conn;
    server authentication:8000 max_fails=2 fail_timeout=5s;
    keepalive 64;
}


upstream new_job_request {
    least_conn;
    server new_job_request:8002 max_fails=2 fail_timeout=5s;
    keepalive 64;
}

upstream bid {
    least_conn;
    server bid:8003 max_fails=2 fail_timeout=5s;
    keepalive 64;
}

# ----------- SERVER -----------
server {
    listen 80 default_server;
    server_name _;

    # Security Headers
    include /etc/nginx/conf.d/headers.conf;

    # Restrict allowed HTTP methods globally (optional, adjust as needed)
    if ($request_method !~ ^(GET|POST|PUT|DELETE|OPTIONS|PATCH)$ ) {
        return 405;
    }

    # Deny access to hidden files (security best practice)
    location ~ /\.(?!well-known) {
        deny all;
    }

    #TODO: Add Logging 

    # ======================
    # Authentication Service
    # ======================
    location /authentication/ {
        include /etc/nginx/conf.d/rate-limit.conf;
        proxy_pass http://auth_service;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_connect_timeout 10s;
        proxy_send_timeout 15s;
        proxy_read_timeout 15s;
        proxy_set_header Connection "";
    }

    # ======================
    # New Job Request Service
    # ======================
    location /new_job_request/ {
        include /etc/nginx/conf.d/rate-limit.conf;
        proxy_pass http://new_job_request;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_connect_timeout 10s;
        proxy_send_timeout 15s;
        proxy_read_timeout 15s;
        proxy_set_header Connection "";
    }

    # ================
    # Bid Service
    # ================
    location /bid/ {
        include /etc/nginx/conf.d/rate-limit.conf;
        proxy_pass http://bid;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_connect_timeout 10s;
        proxy_send_timeout 15s;
        proxy_read_timeout 15s;
        proxy_set_header Connection "";
    }

    # Default fallback: return 404 for everything else
    location / {
        return 404;
    }
}

